--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Farmero14/Sell
build-by-default: true
branches:
- main
projects:
  Sell:
    path: ""
    libs:
      - src: Farmero14/MoneySystem/MoneySystem
        version: ^1.0.0
...
